apiVersion: v1
appVersion: "1.0"
description: An application that regularly scans all containers in a Kubernetes cluster
  for vulnerabilities (AIRGAP compatible)
home: https://helm.estafette.io
icon: https://helm.estafette.io/icon.png
name: estafette-vulnerability-scanner
version: 0.2.0
