apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "estafette-vulnerability-scanner.fullname" . }}-state
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "estafette-vulnerability-scanner.labels" . | nindent 4 }}
{{- if .Values.caCerts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "estafette-vulnerability-scanner.fullname" . }}-cacerts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "estafette-vulnerability-scanner.labels" . | nindent 4 }}
data:
  ca-certificates.crt:
  {{- toYaml .Values.caCerts | indent 4 }}
{{- end }}
